{{- if .Values.turbopass.create -}}
apiVersion: v1
data:
  password: {{ .Values.turbopass.turbosecret | toYaml | b64enc | quote  }}
  username: U0lfMjE4ODc2X0FLU19BRE1JTgo=
kind: Secret
metadata:
  name: turbonomic-credentials
  namespace: turbo
  labels:
    app.kubernetes.io/name: {{ include "kubeturbo.name" . }}
    helm.sh/chart: {{ include "kubeturbo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
{{- end }}